import Head from 'next/head'
import Image from 'next/image'
import Register from './Register'
import Login from './Login'
import Navbar from './Components/Navbar'
import React,{useState,useEffect} from 'react'
import Courses from './Components/Courses'
import { useRouter } from 'next/router';
export default function Home() {
  const [user, setUser] = useState({value:null})
  const [key, setKey] = useState()
  const router = useRouter();
  useEffect(() => {
    
   console.log("Hey useeffect is running at _app.js");
 
     const courseUser = JSON.parse(localStorage.getItem('courseUser'))
     if(courseUser){
      setUser({value:courseUser.token,email:courseUser.email})
      
     }
     setKey(Math.random())
  }, [])

  const logout = ()=>{
    localStorage.removeItem('courseUser')
    setUser({value:null})
    setKey(Math.random())
    router.push('/')
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          
          {/* <Register/> */}
          {/* <Login/> */}
        {key && <Navbar logout={logout} user={user} key={key}  />}
        <Courses user={user}/>
    </div>
  )
}
